spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

